In [1]:
#We are going to implememt Train Test Split Method. In this mthod we will divide our dataset into 80:20
#we will use 80% od data to train our model and rest 20% to test our model accuracy

import pandas as pd

In [2]:
data_frame=pd.read_csv("C:\\Users\\Admin\\Downloads\\carprices.csv")
data_frame

    Mileage  Age(yrs)  Sell Price($)
0     69000         6          18000
1     35000         3          34000
2     57000         5          26100
3     22500         2          40000
4     46000         4          31500
5     59000         5          26750
6     52000         5          32000
7     72000         6          19300
8     91000         8          12000
9     67000         6          22000
10    83000         7          18700
11    79000         7          19500
12    59000         5          26000
13    58780         4          27500
14    82450         7          19400
15    25400         3          35000
16    28000         2          35500
17    69000         5          19700
18    87600         8          12800
19    52000         5          28200

In [3]:
from sklearn.linear_model import LinearRegression 
car_model=LinearRegression()

In [4]:
X=data_frame.drop(['Sell Price($)'],axis=1)
X

    Mileage  Age(yrs)
0     69000         6
1     35000         3
2     57000         5
3     22500         2
4     46000         4
5     59000         5
6     52000         5
7     72000         6
8     91000         8
9     67000         6
10    83000         7
11    79000         7
12    59000         5
13    58780         4
14    82450         7
15    25400         3
16    28000         2
17    69000         5
18    87600         8
19    52000         5

In [6]:
Y=data_frame[['Sell Price($)']]
Y

    Sell Price($)
0           18000
1           34000
2           26100
3           40000
4           31500
5           26750
6           32000
7           19300
8           12000
9           22000
10          18700
11          19500
12          26000
13          27500
14          19400
15          35000
16          35500
17          19700
18          12800
19          28200

In [10]:
from sklearn.model_selection import train_test_split

In [18]:
# Now we will be using the train_test_split() method to define the percentage of data we are using for training and testing.
# This method returns four parameters: X_train and X_test (feature datasets) & y_train and y_test (target datasets).
# We will specify test_size=0.2 to use 20% of the data for testing and 80% for training.
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,test_size=0.2,random_state=42)

#random_state=42 will ensure we get same data for tarining and testing every time we run the code

In [19]:
len(X_train)

16

In [20]:
#It will choose random sample by default
X_train

    Mileage  Age(yrs)
8     91000         8
5     59000         5
11    79000         7
3     22500         2
18    87600         8
16    28000         2
13    58780         4
2     57000         5
9     67000         6
19    52000         5
4     46000         4
12    59000         5
7     72000         6
10    83000         7
14    82450         7
6     52000         5

In [23]:
from sklearn.linear_model import LinearRegression
car_price_model=LinearRegression()

In [24]:
car_price_model.fit(X_train,Y_train)

LinearRegression()

In [26]:
X_test

    Mileage  Age(yrs)
0     69000         6
17    69000         5
15    25400         3
1     35000         3

In [27]:
car_price_model.predict(X_test)

array([[22262.48189206],
       [22571.64380185],
       [38560.99055662],
       [35176.5451397 ]])

In [33]:
car_price_model.score(X_test,Y_test)

0.8360253892678232

In [30]:
Y_test

    Sell Price($)
0           18000
17          19700
15          35000
1           34000

In [34]:
import pickle

In [36]:
with open('car_model.pkl', 'wb') as file:
    pickle.dump(car_price_model, file)

In [37]:
with open('car_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

In [40]:
prediction = loaded_model.predict(X_test)
prediction

array([[22262.48189206],
       [22571.64380185],
       [38560.99055662],
       [35176.5451397 ]])